"""add deals

Revision ID: 6ab78042f839
Revises: f17917f5f272
Create Date: 2026-08-20 11:36:18.486075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab78042f839'
down_revision: Union[str, Sequence[str], None] = 'f17917f5f272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
    'uq_contacts_id_workspace_id',
    'contacts',
    ['id', 'workspace_id'],
)
    op.create_table('deals',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('stage', sa.Enum('lead', 'qualified', 'proposal', 'negotiation', 'won', 'lost', name='deal_stage'), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'workspace_id'], ['companies.id', 'companies.workspace_id'], name='fk_deals_company_workspace'),
    sa.ForeignKeyConstraint(['contact_id', 'workspace_id'], ['contacts.id', 'contacts.workspace_id'], name='fk_deals_contact_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_deals_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index(op.f('ix_deals_workspace_id'), 'deals', ['workspace_id'], unique=False)
    op.create_index('ix_deals_workspace_id_company_id', 'deals', ['workspace_id', 'company_id'], unique=False)
    op.create_index('ix_deals_workspace_id_contact_id', 'deals', ['workspace_id', 'contact_id'], unique=False)
    op.create_index('ix_deals_workspace_id_stage', 'deals', ['workspace_id', 'stage'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        'ix_deals_workspace_id_stage',
        table_name='deals',
    )

    op.drop_index(
        'ix_deals_workspace_id_contact_id',
        table_name='deals',
    )

    op.drop_index(
        'ix_deals_workspace_id_company_id',
        table_name='deals',
    )

    op.drop_index(
        op.f('ix_deals_workspace_id'),
        table_name='deals',
    )

    op.drop_table('deals')

    op.drop_constraint(
        'uq_contacts_id_workspace_id',
        'contacts',
        type_='unique',
    )
    # ### end Alembic commands ###
