"""add deal stage history

Revision ID: 88c4e1b71621
Revises: d1bbf1509fd3
Create Date: 2026-08-26 08:38:40.173232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c4e1b71621'
down_revision: Union[str, Sequence[str], None] = 'd1bbf1509fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_stage_history',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=False),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('changed_by_membership_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id', 'workspace_id'], ['deals.id', 'deals.workspace_id'], name='fk_deal_stage_history_deal_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_deal_stage_history_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_stage_history'))
    )
    op.create_index(op.f('ix_deal_stage_history_workspace_id'), 'deal_stage_history', ['workspace_id'], unique=False)
    op.create_index('ix_deal_stage_history_workspace_id_created_at', 'deal_stage_history', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_deal_stage_history_workspace_id_deal_id', 'deal_stage_history', ['workspace_id', 'deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deal_stage_history_workspace_id_deal_id', table_name='deal_stage_history')
    op.drop_index('ix_deal_stage_history_workspace_id_created_at', table_name='deal_stage_history')
    op.drop_index(op.f('ix_deal_stage_history_workspace_id'), table_name='deal_stage_history')
    op.drop_table('deal_stage_history')
    # ### end Alembic commands ###
