"""add companies and contacts

Revision ID: f17917f5f272
Revises: 5307a8022a67
Create Date: 2026-08-07 17:36:50.049098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17917f5f272'
down_revision: Union[str, Sequence[str], None] = '5307a8022a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('annual_revenue IS NULL OR annual_revenue >= 0', name=op.f('ck_companies_annual_revenue_nonnegative')),
    sa.CheckConstraint('employee_count IS NULL OR employee_count >= 0', name=op.f('ck_companies_employee_count_nonnegative')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_companies_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('id', 'workspace_id', name='uq_companies_id_workspace_id')
    )
    op.create_index(op.f('ix_companies_workspace_id'), 'companies', ['workspace_id'], unique=False)
    op.create_index('ix_companies_workspace_id_domain', 'companies', ['workspace_id', 'domain'], unique=False)
    op.create_index('ix_companies_workspace_id_normalized_name', 'companies', ['workspace_id', 'normalized_name'], unique=False)
    op.create_table('contacts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('normalized_email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile_phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'workspace_id'], ['companies.id', 'companies.workspace_id'], name='fk_contacts_company_workspace'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contacts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_workspace_id'), 'contacts', ['workspace_id'], unique=False)
    op.create_index('ix_contacts_workspace_id_company_id', 'contacts', ['workspace_id', 'company_id'], unique=False)
    op.create_index('ix_contacts_workspace_id_last_name', 'contacts', ['workspace_id', 'last_name'], unique=False)
    op.create_index('uq_contacts_workspace_id_normalized_email', 'contacts', ['workspace_id', 'normalized_email'], unique=True, postgresql_where=sa.text('normalized_email IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_contacts_workspace_id_normalized_email', table_name='contacts', postgresql_where=sa.text('normalized_email IS NOT NULL'))
    op.drop_index('ix_contacts_workspace_id_last_name', table_name='contacts')
    op.drop_index('ix_contacts_workspace_id_company_id', table_name='contacts')
    op.drop_index(op.f('ix_contacts_workspace_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_companies_workspace_id_normalized_name', table_name='companies')
    op.drop_index('ix_companies_workspace_id_domain', table_name='companies')
    op.drop_index(op.f('ix_companies_workspace_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
